### ISSUE TITLE
Fix long name of CNN shows over the details and alignment of selecting bars

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#162]
**Description**
- The long name of CNN job is showing over details in the middle of the screen.

![Image](https://user-images.githubusercontent.com/87486094/195164928-4f0c478a-d638-4ed1-9335-1fd80c3f5839.png)

- The selecting bars are not aligned 

![Image](https://user-images.githubusercontent.com/87486094/195164976-39884365-d8b0-4f31-89d6-400719ad2a77.png)

**Comment by rassokhina-e** [comment]
<img width="438" alt="Screenshot 2022-11-01 at 11 31 31 PM" src="https://user-images.githubusercontent.com/31901584/199344586-e09d3d78-78db-4380-a28b-3d54ce76edb1.png">

**Comment by rassokhina-e** [comment]
<img width="436" alt="Screenshot 2022-11-02 at 1 33 31 AM" src="https://user-images.githubusercontent.com/31901584/199346024-d718c9b3-3c27-4cce-a1d6-4b1fb8edfa8e.png">
