### ISSUE TITLE
Unsubscribe users

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#166]
Original post: [HelpScout #661](https://secure.helpscout.net/conversation/2036402172/661?folderId=6511810)

Description

Unsubscribe this user please lauralucchetti96@gmail.com
> With this letter I ask for the cancellation of the account signed with this e-mail address: [lauralucchetti96@gmail.com](mailto:lauralucchetti96@gmail.com)

**Comment by rassokhin-s** [comment]
Deleted!
