### ISSUE TITLE
Delete duplicate recordings in Tembé Reserve, Brazil (Species) project

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#175]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1666104347616789

**Description**
Delete duplicate files in site **EV18** from https://arbimon.rfcx.org/project/temb-reserve-brazil-species/dashboard

> Site EV18: all recordings are duplicated. I imagine there was an error during the selection of recordings to upload. Would it be possible to eliminate duplicate files?

**Comment by rassokhin-s** [comment]
Fixed
