### ISSUE TITLE
User gets "Error communicating with the server" when deleting site in Arbimon

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#181]
Original post: [HelpScout #667](https://secure.helpscout.net/conversation/2050580903/667?folderId=4147612)

**Description**
User cannot delete site in the project as admin role.
Username: Wendy.Estes-Zumpf@wyo.gov
Project: Wyoming Amphibians

> Hi! I'm an ADMIN on the project Wyoming Amphibians and am trying to remove a bunch of no longer needed sites and recordings. My email is [Wendy.Estes-Zumpf@wyo.gov](mailto:Wendy.Estes-Zumpf@wyo.gov). I am not able delete sites even after I've deleted all recordings within the site. I also cannot rename sites using the edit tool. I get a message that says, "Error communicating with the server". I seem to be able to do all other tasks though like add files, run classifications, delete individual recordings, etc.

**Comment by koonchaya** [comment]
User can delete site but still not able to rename existing site.

**Comment by rassokhina-e** [comment]
I’ve checked all user sites in this project Wyoming Amphibians, synchronized with our core side. The sites which have the ARBIMON ONLY info near with name - Stas is going sync them on this week, I mean for all projects’ sites.
