### ISSUE TITLE
Create soundscapes for the 30 Guardians in the Puerto Rico project

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#183]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1667244110672109

**Description**
> Hello @Ant, we need to create soundscapes for the 30 Guardians in the Puerto Rico project (https://arbimon.rfcx.org/project/puerto-rico-island-wide). The sites are these: GEG1, GEG2, GEG3, GEG4, GEG5, GUG1, GUG2, GUG3, GUG4, GUG5, MAG1, MAG2, MAG3, MAG4, MAG5, RAG1, RAG2, RAG3, RAG4, RAG5, RAG6, SUG1, SUG2 , SUG3, SUG4, SUG5, TOG1, TOG2, TOG3, TOG4, TOG5, TOG6). Each of these sites needs to have a playlist with all the recordings.
It would also be possible to create a soundscape for each site using the following parameters:
- Bin bandwidth: 344Hz
- Aggregation: by month
- Amplitude: 0.1
- Frequency: 0 kHz
- Normalized
@Marconi asked us this urgently as we need to deliver the report soon. Would it be possible to run this on the back end?

> As we need to deliver the report by the end of December and it takes a while to do the analysis post Arbimon, maybe if everything is ready by mid-November it will be great

> Just a reminder that we also need to create soundscapes for 200 locations ( same project, same report, and timeline). Since each location has only ~2,000 recordings we can still create soundscapes using Arbimon frontend, but if we can increase the number of CPUs on the job server or any other tricky in the backend that would be great

**Comment by marconi** [comment]
Hello, thanks for tagging me but I have no idea what this is about. 😸
