### ISSUE TITLE
Change the project owner for user

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#190]
Original post: [Help Scout #604](https://secure.helpscout.net/conversation/1917616350/604?folderId=6511810)

**Description**
Migrate or copy all data from project "[PAPUA 2021](https://arbimon.rfcx.org/project/papua2021/dashboard)" to "[TANAH PAPUA BIO-ACUSTIC MONITORING (WWF)](https://arbimon.rfcx.org/project/tanah-papua-bio-acoustic-monitoring-wwf/dashboard)"
- species
- training sets
- templates
- playlists
- analysis (PM, RFM, soundscapes)

User already transferred sites to new project.

> we already moved the sites yesterday to the new project created by matheus, i was surprised not to see the models and all the analysis that was done. and the option that you propose that he can manage everything from the Papua 2021 project is not an option since this is a WWF project and it is expected to be owned by any wwf staff, which is why we are looking for a way that the creator account is linked to a wwf email. So would you help us to export all the analysis to the new account? no matter if it takes a long time, we will be patient.

**Comment by rassokhina-e** [comment]
Done
