### ISSUE TITLE
Soundscape generation jobs stuck in "waiting"

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#191]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1668172299234989

**Issue description:**
User had Arbimon soundscape generation jobs stuck in "waiting" status for 2 days.
They've hid and re-created all jobs and a few times over. Currently, they have only one job in one of their projects (linked below) that's in "waiting" status.

**Additional details:**
https://arbimon.rfcx.org/project/selenkay-survey-1/jobs

**Comment by koonchaya** [comment]
Jobs are completed.

**Comment by koonchaya** [comment]
Jobs are not showing on analysis page.

**Comment by antonyharfield** [comment]
The jobs did not complete successfully, so I've queued them to run again. Please check again tomorrow.

**Comment by koonchaya** [comment]
There is 1 job is still in waiting status.

![Image](https://user-images.githubusercontent.com/87486094/203464928-d5c27db3-f319-457d-8ba6-81eb61b674cd.png)

**Comment by koonchaya** [comment]
![Image](https://user-images.githubusercontent.com/87486094/203696643-6fa3f6d2-f99a-4eed-a0f0-ec2d3432eb5e.png)

**Comment by koonchaya** [comment]
![Image](https://user-images.githubusercontent.com/87486094/203899845-8bd56abf-800b-45e9-8795-6103be0ccfd8.png)
