### ISSUE TITLE
RFM analysis are stuck at waiting status

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#196]
Original post: Help Scout#673

Description
Random Forest Model jobs are on waiting status.
Project: Raucat https://arbimon.rfcx.org/project/raucat/jobs

![Image](https://user-images.githubusercontent.com/87486094/202058481-6fa8ceda-223c-4a6e-a02e-b8bca9002ed3.png)

**Comment by koonchaya** [comment]
The jobs are running

![Image](https://user-images.githubusercontent.com/87486094/202441490-403df8c9-cdec-4ed2-9514-4c43327f21de.png)

**Comment by antonyharfield** [comment]
Re-queued these jobs too. Check again in 24 hours.

**Comment by koonchaya** [comment]
There are some of the jobs in stalled status and waiting status.

![Image](https://user-images.githubusercontent.com/87486094/203465311-44a17062-899b-4276-a4af-da1b4868a566.png)

**Comment by koonchaya** [comment]
![Image](https://user-images.githubusercontent.com/87486094/203696929-80d40831-ec20-4d7f-a1d3-b9d0b0752b99.png)

**Comment by koonchaya** [comment]
Ask the user re create the job.

**Comment by koonchaya** [comment]
![Image](https://user-images.githubusercontent.com/87486094/205787326-1f166f7e-3856-490f-9294-92e17dc5c001.png)
