### ISSUE TITLE
Files are not uploaded on Uploader app

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#197]
Original post: Help Scout #675

Description
> I have now some problems with uploading my files. I load all the files normally in the uploader, and then, I start the upload process. But the process doesn't proceed, it still takes many hours as the photo shows: the selected files don't upload to the platform.

![Image](https://user-images.githubusercontent.com/87486094/202328472-1b3ebf3c-49d1-47d4-af54-a8539529a40b.png)

**Comment by rassokhina-e** [comment]
https://rfcx.slack.com/archives/C02G4AR2GEL/p1668676106180769?thread_ts=1668672000.810789&cid=C02G4AR2GEL

**Comment by koonchaya** [comment]
Screenshots from user

![Image](https://user-images.githubusercontent.com/87486094/202711063-b7b94f27-ecd6-445b-9593-f8683862f092.png)



![Image](https://user-images.githubusercontent.com/87486094/202711105-f7ea440e-5644-43e8-84c1-ab0b2d3c7379.png)



![Image](https://user-images.githubusercontent.com/87486094/202711162-eb1c7fc3-f86c-4e10-850e-82b170767149.png)

**Comment by koonchaya** [comment]
I notified user about v 1.5.2 released. Waiting for the feedback.
