### ISSUE TITLE
Create Python SDK for uploading files from AudioMoths

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#198]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1668522689578189

Description
The Python SDK should be done by the end of Jan 2023

> please find in attachment project information summary, and below timeline connected with regulations included in our conservation plan (the main planing document of Białowieża NP) with suggested number of used AudioMoths devices:

1. end of the test phase (70 AudioMoths) end of January 2023
2. wolves and lynx mating season monitoring (~35 AudioMoths) from February to March 2023
3. birds (included in conservation plan) monitoring (70 AudioMoths) from April to mid-May 2023
4. rare birds species monitoring (~35 AudioMoths) from mid-May to July 2023
5. amphibians monitoring (Bombina Bombina) (~10 AudioMoths) from June to July 2023
6. bats monitoring (~35 AudioMoths) from June to August 2023
7. birds activity monitoring during the Autumn (included in conservation plan) (~35 AudioMoths) from September to October 2023

The above plan is strictly connected with our yearly taken monitoring activities. This time we hope effectively use the AudioMoths in connection with monitoring methods we have used so far.

I have some question according to AudioMoth's recordings upload process. I've found RFCx's python SDK (https://github.com/rfcx/rfcx-sdk-python/releases). Is it possible to use it with some automation bash script to  upload recordings. Of course I've found dedicated app, but it seems that it requires constant user supervision...

According to Arbimont web service, here is the temporary name of our project: BPN-TestProject

**Comment by antonyharfield** [comment]
I've contacted the user already.
