### ISSUE TITLE
Improvement of when search with the name of species in Arbimon

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#204]
Original post: Help Scout #676

**Description**
User was trying to find Rhamphastos dicolorus species and add to the project but she could not find it by searching with the full name. I tried with the other part of the name and it works.

https://user-images.githubusercontent.com/87486094/203097534-41439344-9687-47d4-89f9-83c93b780902.mov

**Comment by antonyharfield** [comment]
Let's close this issue, the species looks like it is spelt correctly https://en.wikipedia.org/wiki/Green-billed_toucan.
