### ISSUE TITLE
User cannot find soundscape job in Selenkay Survey 2 project

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#210]
Original post: gmail

**Description**
Project: https://arbimon.rfcx.org/project/selenkay-survey-2/dashboard
> I still have no access to the soundscapes in Survey 2, just like before in Survey 1. I am looking for **Soundscape-Amplitude_02-Normalized_Selenkay-Survey-2_Site_Transect-XC**. Here is what I see for Survey 2:

![Image](https://user-images.githubusercontent.com/87486094/204068267-d051d991-e2a9-4802-b5fc-d3f9764560d8.png)

Here is the same view filtered:

![Image](https://user-images.githubusercontent.com/87486094/204068275-9dd768e2-5aac-4df0-8aa3-80f3ff4b3712.png)

**Comment by koonchaya** [comment]
Jobs are in waiting status


![Image](https://user-images.githubusercontent.com/87486094/204423522-8a1505bf-64dc-4192-8cce-e03731a159a4.png)

**Comment by antonyharfield** [comment]
I think all jobs are complete now.

**Comment by koonchaya** [comment]
All good now
