### ISSUE TITLE
First dataset shows no data on Richness Insight reports

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#213]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1669734967013459

**Description**
Product: Biodiversity Reports

**Issue description:**
On the Species Richness tab of the Insights page adding the Taxon filter results in the site returning 'no data' for all fields

**Steps to reproduce:**
Go to the Puerto Rico Island-Wide page, select the richness tab, click on the comparison box and add a taxon filter for birds

**Expected result:**
richness data will be filtered to display results for bird species only

**Actual result:**
no data is displayed

**Additional details:**
https://bio.rfcx.org/puerto-rico-island-wide/richness

[Screen recording](https://rfcx.slack.com/archives/C03FD1WD02J/p1669735011222009?thread_ts=1669734967.013459&cid=C03FD1WD02J)

https://user-images.githubusercontent.com/87486094/204705725-7a3e88ab-c94d-4b9d-86c9-32de2cc15260.mov

The first dataset only works when select all taxon. The second dataset did not show any thing either. It looks like the filter works with all taxon only.

![Image](https://user-images.githubusercontent.com/87486094/204706083-40a11399-cbfc-42bb-8a09-b361e195ac33.png)

**Comment by rassokhina-e** [comment]
Fixed!
