### ISSUE TITLE
Cancel RFM job

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#233]
Original post: Help Scout #688

> Can you cancel a job/model classification after it has started? I already ran the classification on that site.

Project: https://arbimon.rfcx.org/project/usfws-wyoming-toad/jobs

![Image](https://user-images.githubusercontent.com/87486094/208005489-eb6918a2-4fe6-45a5-b87c-a281376acdff.png)

**Comment by rassokhina-e** [comment]
@antonyharfield What do you think is it possible to cancel the running RFM job?
