### ISSUE TITLE
Fix recording timestamps from BDFFP Acoustics and delete duplicate files

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#235]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1671461224506299

**Issue description:**
Hi guys, the recordings for this project are 1h ahead (https://arbimon.rfcx.org/project/bdffp-acoustics/visualizer/rec/89617494/?gain=15). The correct thing would be for a recording at 2 am to be at 3 am. Additionally each recording in this project has 5 copies.

**Steps to reproduce:**
1. Go to: https://arbimon.rfcx.org/project/bdffp-acoustics/visualizer/rec/89617494/?gain=15
2. Visualizer and chose one day.
3. See the extra copies of each recording.

**Expected result:**
The recordings must be time corrected and with only 1 copy each.

**Actual result:**
All recordings are 1h ahead and 5 copies each.

**Additional details:**
BDFFP Acoustics: https://arbimon.rfcx.org/project/bdffp-acoustics/visualizer/rec/89617494/?gain=15

I checked and see that there are duplicate files with different uploaded time.

![Image](https://user-images.githubusercontent.com/87486094/208575780-6fe3aedd-3e27-4506-a8a1-1ef362c44432.png)

**Comment by rassokhin-s** [comment]
@koonchaya this should be fixed. I noticed that "duplicate" files had different deployment id in the Comments column, so I deleted recordings based on that and kept only two deployments (check first and last page).

Here is a list of deleted deployments:
```
243B1F075C7B3FFC
249BC3055C0300C4
249BC3055C0301F5
247AA5015C03008B
247AA5015C02D027
249BC3055C02FB0D
247AA5015C030554
249BC3055C02FAEB
249BC3055C0301C9
247AA5015C02FA29
249BC3055C0301EA
247AA5015C02FBA0
```
