### ISSUE TITLE
The number of site between Arbimon and Companion app is not match

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#236]
Original post: [Help Scout #689](https://secure.helpscout.net/conversation/2102766097/689?folderId=6511810)

**Description**
Site "Sh14" is not on Arbimon website but there are 3 on Companion.

> I was going to reach out to ask you! I did not create duplicate sites but I did receive some sync errors during deployment from lack of cell service. I used the RFCx Companion app to for deployment. I deleted the duplicates, but I do need help with 1 of my deployments. It is showing up as a duplicate in the app, but is not visible at all on the RFCx website. It is named "Sh14". On the companion app it's showing up as 3 deployments, there should only be 1.

**Additional details**
Project: https://arbimon.rfcx.org/project/amwo-soundscapes/audiodata/sites
Site name: Sh14
Email: christinak@ou.edu

**Comment by rassokhin-s** [comment]
Data unsync and a possible reason of it have been fixed @koonchaya

**Comment by koonchaya** [comment]
@Tooseriuz @rassokhin-s User replied
> There are 3 duplicates. Lsd29, Ox34, Ox17 are duplicates. The Ox34 duplicate I deleted from the app in the field but still is on my companion app. There is also no button or gesture I can use to refresh the app besides restarting it.


![Image](https://user-images.githubusercontent.com/87486094/211697778-53aae42d-3434-4a0d-915e-eae40ba3aa55.png)



![Image](https://user-images.githubusercontent.com/87486094/211697794-95a925b8-27be-452d-818e-c50c2e7a2421.png)



![Image](https://user-images.githubusercontent.com/87486094/211697807-a9b24ce3-4651-421c-b4ca-b03b0030dd2c.png)
