### ISSUE TITLE
Fix recording timestamps in WeForest project

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#242]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1672833527806679

**Issue description:**
Hey guys, one of the sampling sites with recordings from 2022 of the WeForest Wildlife Corridors project (https://arbimon.rfcx.org/project/weforest-wildlife-corridors/visualizer/rec/96553402) has a difference of 3 h in the recordings of the IPE22 site. Recordings are 3 hours ahead.

**Steps to reproduce:**
1. Go to: https://arbimon.rfcx.org/project/weforest-wildlife-corridors/visualizer/rec/96553402
2. open a record in any day of 2022
3. check the difference in the Arbimon time and in the recording file name

**Expected result:**
The time display in the Arbimon visualizer should be the same than the recording file name.

**Actual result:**
A difference of three hours between the time displayed in Arbimon and the recording file name.

**Additional details:**
https://arbimon.rfcx.org/project/weforest-wildlife-corridors/visualizer/rec/96553402
**The issue is just in the site IPE22**

![Image](https://user-images.githubusercontent.com/87486094/210686878-63551b1a-1df2-4656-8d38-b4070921a544.png)

**Comment by rassokhin-s** [comment]
This is done
