### ISSUE TITLE
User cannot see all sites of "Barragem Duas Pontes" project in Uploader app

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#258]
Original post: email with [fernandomdhorta@gmail.com](mailto:fernandomdhorta@gmail.com)

Description
> when I try to upload files to the project "Barragem Duas Pontes", using UPLOADER, I can only see part of the sites (DP01, DP02, DP03, DP04, DP09, DP10, DP11 and DP12). The others (DP05, DP06, DP07, DP08, DP23 and DP24) are not accessible.
I talked with other "Barragem Duas Pontes" user. He is facing the same problem.

**Comment by rassokhina-e** [comment]
![Image](https://user-images.githubusercontent.com/31901584/212730847-dae1cd95-c64c-45f5-8296-c9e1ae5f3bb1.png)

**Comment by rassokhina-e** [comment]
![Image](https://user-images.githubusercontent.com/31901584/212843107-a5b21f75-96bc-41d7-aebc-6d2cb6c7c871.png)
