### ISSUE TITLE
User gets 503 service unavailable errors often in the last few weeks

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#267]
Original post: [Help Scout #707](https://secure.helpscout.net/conversation/2132216260/707?folderId=6511810)

**Description**
What is 503 error?

> I have noticed that in the last few weeks I have been getting a lot of 503 service unavailable errors when attempting to load recordings in the Data/Recordings/Open in new tab.

> This wasn't an issue in the recent past. Has something changed? Is this unique to my account?

**Comment by rassokhina-e** [comment]
Project name:

**Comment by koonchaya** [comment]
503 is still coming up if I open tabs. See attached screenshot and note date and time in lower right hand corner as well as the 4th tab with 503. First tab never opened, and I got the red "Network Error" message briefly on the screen.



![Image](https://user-images.githubusercontent.com/87486094/219547064-6e5d42dc-2041-4b65-8821-9efcca8087a8.png)

My workaround is to not use the "open in new tab", though it really speeds up my analysis if I can utilize the open tabs feature.
