### ISSUE TITLE
Detected audio of species numenius-arquata is showing "No data" in Cratere degli Astroni - RNS

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#270]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1674754916982679

**Issue description:**
Recent Huawei blog features species being monitored in Italy - they link to Insights page so that readers can hear the species and get more info on them. The Eurasian Curlew is currently displaying "no data" in the audio section, disallowing people to listen in.

**Steps to reproduce:**
1. Click link used in blog > https://bio.rfcx.org/cratere-degli-astroni-rns/spotlight/numenius-arquata
2. See "Detected audio" section

**Expected result:**
Audio data featured enabling viewers to hear the species

**Actual result:**
no audio data showing, nothing to press play to listen to

**Additional details:**
Arbimon Insights > Cratere degli Astroni - RNS > Eurasian Curlew Species Spotlight.

Link > https://bio.rfcx.org/cratere-degli-astroni-rns/spotlight/numenius-arquata

List of additional species showing no data
- anas-platyrhynchos
- anser-anser
- ardea-cinerea
- ardea-purpurea -no picture too
- cettia-cetti
- chroicocephalus-ridibundus
- cisticola-juncidis
- coracias-garrulus
- corvus-monedula
- coturnix-coturnix
- dendrocopos-major
- erithacus-rubecula
- falco-tinnunculus
- fulica-atra
- ichthyaetus-melanocephalus
- larus-cachinnans
- larus-michahellis
- parus-major
- phalacrocorax-carbo
- phasianus-colchicus
- phoenicopterus-roseus
- phylloscopus-collybita
- pica-pica
- rallus-aquaticus
- recurvirostra-avosetta
- remiz-pendulinus
- sylvia-melanocephala
- tringa-nebularia
- turdus-merula

**Example screenshot**

![Image](https://user-images.githubusercontent.com/87486094/215022534-a2c4f171-8b46-4c95-a19c-26730c38597f.png)

**Comment by rassokhina-e** [comment]
the feedback for the [numenius-arquata](https://bio.rfcx.org/cratere-degli-astroni-rns/spotlight/numenius-arquata) species:

the user can not see the audio for the "numenius-arquata" on the Insights page because the original recording, related to this template on the Arbimon side - non-core rfcx recording. I mean this is the old Arbimon recording which we do not keep in the core database. Originally, when the templates sync logic was built it was the requirement to support on the Insight page only those recordings which were uploaded with the Uploader app.

**Comment by rassokhina-e** [comment]
List of additional species showing no data

anas-platyrhynchos ---> the old, non-core rfcx recording related to this species template
anser-anser ---> there is not any templates on the Arbimon side
ardea-cinerea ---> there is not any templates on the Arbimon side
ardea-purpurea -no picture too ---> the old, non-core rfcx recording related to this species template, photo is fixed!
cettia-cetti ---> the old, non-core rfcx recording related to this species template
chroicocephalus-ridibundus ---> the old, non-core rfcx recording related to this species template
cisticola-juncidis ---> there is not any templates on the Arbimon side
coracias-garrulus ---> there is not any templates on the Arbimon side
corvus-monedula ---> the old, non-core rfcx recording related to this species template
coturnix-coturnix ---> there is not any templates on the Arbimon side
dendrocopos-major
erithacus-rubecula
falco-tinnunculus
fulica-atra
ichthyaetus-melanocephalus
larus-cachinnans
larus-michahellis
parus-major
phalacrocorax-carbo
phasianus-colchicus
phoenicopterus-roseus
phylloscopus-collybita
pica-pica
rallus-aquaticus
recurvirostra-avosetta
remiz-pendulinus
sylvia-melanocephala
tringa-nebularia
turdus-merula

**Comment by rassokhina-e** [comment]
We need to create a migration process the old Arbimon recordings to the Core db. Let's plan this work to the next sprint

**Comment by koonchaya** [comment]
**No data on bio**

- anser-anser
- ardea-cinerea
- ardea-purpurea
- chroicocephalus-ridibundus
- cisticola-juncidis
- coracias-garrulus
- coturnix-coturnix
- dendrocopos-major
- fulica-atra
- ichthyaetus-melanocephalus
- larus-cachinnans
- phasianus-colchicus
- recurvirostra-avosetta

**Comment by rassokhina-e** [comment]
The project has not these species templates, this is the reason!
