### ISSUE TITLE
Fix timestamp of recordings in Tembe Project

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#276]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1675091055192519

**Issue description:**
Timestamp issues on some Tembe Project sites.
There are sites that the dawn chorus is starting 1 hour earlier, other sites 2 hours late and some 3 hours late

**Steps to reproduce:**
Project Tembe (species) go to Visualizer open the site, the dawn chorus is to start between 5:30 - 6:00. But on some sites it starts at 4:30, or 7:30 or 8:30.

**Expected result:**
Dawn chorus more or less 5:30.

**Actual result:**
Sites com dawn chorus at 4:30 **(+1 hour from the current time)**:
AR02
GP01
GP02
GP03
GP04
GP05
GP06
GP07
GP10
PÇ03
PÇ09
Sites com dawn chorus at 7:30 **(-2 hours from the current time)**:
AR03
AR04
GP09
PÇ01
PÇ04
PÇ05
PÇ06
PÇ07
PÇ08
PÇ11
PÇ12
Sites com dawn chorus ate 8:30 **(-3 hours from the current time)**
CA07
CR01

**Additional details:**
https://arbimon.rfcx.org/project/temb-reserve-brazil-species/dashboard

**Comment by rassokhin-s** [comment]
Sites com dawn chorus at 4:30 (+1 hour from the current time):
AR02 in progress
GP01
GP02
GP03
GP04
GP05
GP06
GP07
GP10
PÇ03
PÇ09
Sites com dawn chorus at 7:30 (-2 hours from the current time):
AR03
AR04
GP09
PÇ01
PÇ04
PÇ05
PÇ06
PÇ07
PÇ08
PÇ11
PÇ12
Sites com dawn chorus ate 8:30 (-3 hours from the current time)
CA07
CR01
