### ISSUE TITLE
The spectrogram in the left window does not correspond to the main spectrogram

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#277]
Original post: Help Scout #710

The spectrogram in the left window does not correspond to the main spectrogram 
https://arbimon.rfcx.org/project/impacts-of-anthropogenic-fire-on-bird-communities/visualizer/rec/101051419

![Image](https://user-images.githubusercontent.com/87486094/215649939-78695ce9-f0fa-4ac5-bd53-4492312951f5.png)

**Comment by koonchaya** [comment]
I checked the same spectrogram today. They look the same.


![Image](https://user-images.githubusercontent.com/87486094/215653899-44767611-098b-4445-a1a2-f49f54d7587e.png)

**Comment by rassokhina-e** [comment]
https://arbimon.rfcx.org/project/impacts-of-anthropogenic-fire-on-bird-communities/audiodata/recordings

17 page

**Comment by rassokhina-e** [comment]
@koonchaya Fixed the 17-page problem!
