### ISSUE TITLE
Opening recordings in visualizer get error/not load

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#289]
Original post: Help Scout #707

**Description**
Error and not loading in visualizer.

**Screenshot**
https://drive.google.com/file/d/1aPe5K4Wwe8vrye8z501D3-drD-jOaJ64/view

**Comment by koonchaya** [comment]
Site: 2021 Panoche Creek Preserve 1W
Original file name: PCP1Wam-2021-04-19_08-00.flac
https://arbimon.rfcx.org/project/tricolored-blackbird-breeding-phenology/visualizer/rec/52702642/
I’ve just fixed this file and different ones from this site, which I found without the filename:
{“filename”:“PCP1Wam-2021-04-21_07-40.flac”},
{“filename”:“PCP1Wam-2021-05-04_14-00.flac”},
{“filename”:“PCP1Wam-2021-05-04_18-00.flac”},
{“filename”:“PCP1Wam-2021-05-07_11-00.flac”},
{“filename”:“PCP1Wam-2021-05-16_10-00.flac”},
{“filename”:“PCP1Wam-2021-05-16_16-00.flac”},
{“filename”:“PCP1Wam-2021-05-16_17-00.flac”},
{“filename”:“PCP1Wam-2021-05-23_06-40.flac”},
{“filename”:“PCP1Wam-2021-05-25_17-00.flac”},
{“filename”:“PCP1Wam-2021-07-07_03-20.flac”}

**Comment by koonchaya** [comment]
503 is still coming up if I open tabs. See attached screenshot and note date and time in lower right hand corner as well as the 4th tab with 503. First tab never opened, and I got the red "Network Error" message briefly on the screen.



![Image](https://user-images.githubusercontent.com/87486094/219550191-826e75f7-047c-4586-9ba1-8d5a9bcbdbe7.png)



My workaround is to not use the "open in new tab", though it really speeds up my analysis if I can utilize the open tabs feature.

**Comment by koonchaya** [comment]
https://drive.google.com/file/d/1nO4FkciIhwgnVBn5R5VyVuPjOuITaw2b/view?usp=sharing

**Comment by rassokhina-e** [comment]
@koonchaya Maybe the adblocker or antivirus is a reason
