### ISSUE TITLE
User cannot find the existing site in Uploader app

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#298]
Original post: Help Scout #721

**Description**
User cannot find site name "Sitio1" in Bacalar project https://arbimon.rfcx.org/project/bacalar/dashboard in Uploader app. User tried to search for this site already.

**Comment by rassokhina-e** [comment]
This site is at the bottom of the list!
<img width="1004" alt="Screenshot 2023-02-16 at 1 05 00 PM" src="https://user-images.githubusercontent.com/31901584/219318554-caad9258-4181-4d65-a2ff-ff458661d38c.png">
