### ISSUE TITLE
Fix timestamp of recordings in Sounds of Atlantic Forest project

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#336]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1685970730636719

**Issue description:**
The partners reported timestamping issues for some sampling sites in the project. This is a very important partneship and the issue is blocking the partner. Additionally, we (science team) have a CNN deliverable associated with this dataset (due August). Therefore, this issue will soon block our workflow as well.
Therefore, we would check with the technical team, what is the best solution to deal with this issue?

**Steps to reproduce:**
1. Open the project in Arbimon
2. Go to the "Visualizer" tab and select one of the sample sites with a timestamping issue
Here is a list of 12 sampling sites with timestamping issues (the list is partial, since the partner checked only 10% of sites):
SC_B15P015GIPE19
SC_B15P010GIPE66
SC_B15P014GIPE49
SC_B15P013GIPE46
SC_B01P066GIPE61
SC_B02P085GIPE23
SC_B02P082GIPE18
SC_B02P086GIPE70
SC_B02P083GIPE81
SC_B02P087GIPE86
SC_B04P080GIPE64
SC_B04P081GIPE90

**Expected result:**
The correct time for the recordings.

**Actual result:**
The sites reported are 2 or 3 hours difference from what would be correct.

**Additional details:**
Sounds of Atlantic Forest
https://arbimon.rfcx.org/project/sounds-of-atlantic-forest/dashboard

**Comment by koonchaya** [comment]
@rassokhin-s Please fix timestamps in the sites from this sheet. We need to match recorded time with the filename. You will see the time difference 2 and 3 hours but we will make them match with filename.

[ArbimonTimestamp_Sounds of Atlantic Forest.xlsx](https://github.com/rfcx/engineering-support/files/11772163/ArbimonTimestamp_Sounds.of.Atlantic.Forest.xlsx)

**Comment by rassokhin-s** [comment]
SC_B15P015GIPE19 done
SC_B15P010GIPE66 done
SC_B15P014GIPE49 done
SC_B15P013GIPE46 done
SC_B01P066GIPE61 done
SC_B02P085GIPE23 done
SC_B02P082GIPE18 done
SC_B02P086GIPE70 done
SC_B02P083GIPE81 done
SC_B02P087GIPE86 done
SC_B04P080GIPE64 done
SC_B04P081GIPE90 done

**Comment by rassokhin-s** [comment]
+ SC_B11P149GIPE44
+ SC_B12P057GIPE71
- SC_B18P167GIPE67 - no such site
+ SC_B28P034GWF04
+ SC_B31P154GIPE14
+ SC_B26P002GIPE23
+ SC_B18P164GIPE29
