### ISSUE TITLE
Restore corrupted files from migrated legacy projects

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/engineering-support#340]
Examples
- https://arbimon.rfcx.org/project/mitsinjo_url/visualizer/rec/977074
- https://arbimon.rfcx.org/project/elevation/audiodata/recordings
- https://arbimon.rfcx.org/project/jaguas-2012-2013-pruebas/audiodata/recordings

Conversation with Marconi and Carly https://rfcx.slack.com/archives/C05B3FC1ZFX/p1686960587955589

**Comment by koonchaya** [comment]
1. https://arbimon.rfcx.org/project/mitsinjo_url/visualizer/rec/977074
Done

2. https://arbimon.rfcx.org/project/elevation/audiodata/recordings
In progress

3. https://arbimon.rfcx.org/project/jaguas-2012-2013-pruebas/audiodata/recordings
No legacy recordings
