### ISSUE TITLE
Move corrupted files from rfcx-streams-production to another bucket (cold storage)

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/engineering-support#355]
All arbimon analyses read audio files directly from the bucket for performance reasons. While there are corrupted files in the bucket, these files are included in analyses. Therefore it is critical we remove the corrupted files to ensure the jobs are skipping corrupted files.

Alternative ideas:
- Load files from media API => slows job performance, increases load on media API
- Duplicate `availability` column to Arbimon db => increases the amount of data to keep in sync
-

**Comment by rassokhina-e** [comment]
@koonchaya can you please check this task?

**Comment by rassokhin-s** [comment]
1) All corrupted files between `1970-01-01` and `2100-01-01` have been copied into `rfcx-streams-production-corrupted` bucket with deep archive storage class
2) All corrupted files between `1970-01-01` and `2100-01-01` have been marked with delete marker.

Once we make sure that everything is good, I can go and completely delete noncurrent versions of these files to free up space.

**Comment by rassokhina-e** [comment]
@koonchaya can you please check each type of job on the Arbimon side, we have to check any playlist with a corrupted file into it

**Comment by koonchaya** [comment]
@rassokhina-e I ran all types of jobs here https://arbimon.rfcx.org/project/the-green-place-phitsanulok/jobs
