### ISSUE TITLE
Upload all existing models to Core

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/engineering-support#357]
Models to be uploaded
- [x] asian-elephant v3

- [x] birds-sumatra v2 - mentioned there is a v2
- [x] pr-parrot - we have v1, is there a v2?
- [x] BCI Panama*
- [x] Mexico*
- [x] PDBFF Brazil*

Ant to talk to Frongs:
- [x] asian-elephant-edge v3 - the tflite version of above

*needs a name

Models already in Core
```
asian-elephant-edge v2
birds-western-amazon v2
pr-parrot v1
spider-monkey v3
squirrel v1
whale v1
whale-orca v1
```

**Comment by nnbuainain** [comment]
uploaded the following models

lemur - id 102
mexico - 103
pdbff - 104

**Comment by nnbuainain** [comment]
Recently uploaded CNNs:

Puerto rico v.3.2 - id 105 (I'm assuming this is the new version of the pr-parrot v1 but i'm not sure)

**Comment by nnbuainain** [comment]
Recently uploaded 

BCI Panama

Sumatra v2

Asian elephant tflite is ready and with frongs. should I upload to db?
