### ISSUE TITLE
Run script for corrupted data in the requested projects

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#361]
We need to run script to analyze the corrupted data in these following projects (requested from Carly, Mahreen)

- Sounds of Atlantic Forest**
- WWF IT - Agribioacoustic project**
-  Alpine Frogs a Calling (alpine-frogs-a-calling)
- Box-Ironbark - Ecosystem Resilience Project (box-ironbark-ecosystem-resilience-project)
- High Altitude Shrubland - Ecosystem Resilience (high-altitude-shrubland-ecosystem-resilience)
- Karen Rowe’s project (1538-karen-project)
- Listening for Nature - Australia (listening-for-nature-australia)
- Listening for Nature - Indonesia (listening-for-nature-indonesia)
- Mallee - Ecosystem Resilience Project (mallee-ecosystem-resilience-project)
- Monitoring Nillumbik’s Forests (monitoring-nillumbik-s-forests)
- Tall Mixed Forest - Ecosystem Resilience Project (tall-mixed-forest-ecosystem-resilience-project)
- DEEP PROJECT SUMATRA
- WatchOut - Kopacki rit Nature Park, Croatia

**Comment by antonyharfield** [comment]
Updated docs and spreadsheet
