### ISSUE TITLE
Rerun the script to check corrupted files after reuploaded

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#371]
List of the projects need to run script

- [x] [Peru Flooded Forests Soundscape](https://arbimon.rfcx.org/project/peru-flooded-forest-soundscape/dashboard)
- [x] [Puerto Rico Island-Wide](https://arbimon.rfcx.org/project/puerto-rico-island-wide/dashboard)
- [x] [WWF IT - Agribioacoustic project](https://arbimon.rfcx.org/project/wwf-it-agribioacoustic-project/dashboard)
- [x] [Ingleside Sandsheet Ponds](https://arbimon.rfcx.org/project/ingleside-sandsheet-ponds/dashboard)
- [x] [Gainesville Urban Gradient](https://arbimon.rfcx.org/project/gainesville-urban-gradient/dashboard)
- [x] [Listening for Nature - Australia](https://arbimon.rfcx.org/project/listening-for-nature-australia/dashboard)
- [x] [Listening for Nature - Indonesia](https://arbimon.rfcx.org/project/listening-for-nature-indonesia/dashboard)
- [x] [Tall Mixed Forest - Ecosystem Resilience Project](https://arbimon.rfcx.org/project/tall-mixed-forest-ecosystem-resilience-project/dashboard)
- [x] [Aammiq Survey](https://arbimon.rfcx.org/project/aammiq-survey/dashboard) (New project) cj569ug01av4
- [x] [Colombia - Audiomoth Humboldt Inst](https://arbimon.rfcx.org/project/colombia-audiomoth-humboldt-inst/dashboard)
- [x] [Hutan Harapan (P4F)](https://arbimon.rfcx.org/project/hutan-indo/dashboard)

**Comment by antonyharfield** [comment]
Gainesville Urban Gradient - no corrupted files

**Comment by antonyharfield** [comment]
> Listening for Nature - Australia and Indonesia

There is no point doing this until we've restored all the data

**Comment by antonyharfield** [comment]
> Tall Mixed Forest - Ecosystem Resilience Project

There is no change. Looks like nothing has been re uploaded.

**Comment by antonyharfield** [comment]
> Aammiq Survey

Done: https://docs.google.com/document/d/1ZROQAPBtcr6PRC0ZUbc1IfJSc3oEdYLkwVHWPIrt8Kg/edit

**Comment by antonyharfield** [comment]
> Colombia - Audiomoth Humboldt Inst

No corrupted files
