### ISSUE TITLE
Duplicate recordings in the same day in the different site

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#377]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1689688198573309

>We found duplicate recordings on the same day, but in different sites.
Question to the tech team - This is very worrisome. We should give high priority to understand how and why this is happening.

![Image](https://user-images.githubusercontent.com/87486094/254461297-4f4ab350-cd73-4da5-91ad-b6b6e46f6b4e.png)

**Comment by koonchaya** [comment]
Asked for original files (from the screenshot) - waiting for files

**Comment by koonchaya** [comment]
original files https://rfcx.slack.com/archives/D01KAJWP6FN/p1690173623512489

After uploaded files, see spectrograms


![Image](https://github.com/rfcx/engineering-support/assets/87486094/0a7cfd42-fa0f-4efb-b223-018e871e6be8)
![Image](https://github.com/rfcx/engineering-support/assets/87486094/ffff7b8a-947f-4340-8b98-ac8fa0aab44c)

**Comment by antonyharfield** [comment]
We are going to delete the recordings from GHI03 `z3uo303smwj3` between 2023-04-03 and 2023-04-11.

**Comment by rassokhina-e** [comment]
Done!
