### ISSUE TITLE
Fix timestamp Sounds of Atlantic project

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#386]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1690469813296659?thread_ts=1685970730.636719&cid=C03FD1WD02J

Project: Sounds of Atlantic 
Site: SC_B18P157GIPE67 and SC_B31P154GIPE14

**Comment by rassokhin-s** [comment]
SC_B18P157GIPE67 in progress
SC_B31P154GIPE14
