### ISSUE TITLE
WWF IT move recordings to correct S3 location

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/engineering-support#387]
There are 10 sites that are affected, the 5 MSEL sites might be easier to restore so we will try them first.

Need to check which timezone is correct.

See analysis https://docs.google.com/document/d/17kejTbmWP4si25lBIVpg3o8-C_XsfSVw8UtiLH4kj10/edit

**Comment by antonyharfield** [comment]
If we could remove the incorrect files from the 5 difficult sites then that could also

**Comment by rassokhin-s** [comment]
ATRI08
ATRI10
ATRI12
ATRI28
ATRI31
GHI03
MSEL17 fixed in `MSEL17_fixed`
MSEL25
MSEL29
MSEL44
MSEL45

**Comment by koonchaya** [comment]
Delete sites listed above
