### ISSUE TITLE
Check site HH_AUD059 in P4F project corrupted/duplicates

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#398]
We think this was caused by the reupload bug in the past weeks.

For a good example, look at 07:00 on 2023-03-1 in HH_AUD059. https://arbimon.rfcx.org/project/hutan-indo/visualizer/rec/129839919 There are 5 recordings at the same time. They are all unavailable, but when you check the db in Core only 1 is unavailable -- the duplicates were created on reupload.

We can see the problem affects ~1,500 recordings, mostly in HH_AUD059 but also in a few other sites:
```sql
select stream_id, start, count(1) total from stream_segments
where stream_id in ('q1xqaif4qyqy','vn57la9kuqhd','nzr9ff4h0ffl','hydi2au0s07d','nnv4kk0latf5','iewvjt06rrwr','ojufem6lekbr','uwt3l308rvoq','mm0qjevukg7r','dtampl8sc82z')
      and start between '2023-01-01' and '2023-05-01'
group by 1, 2
having count(1) > 1
order by 1, 2;
```

**Comment by antonyharfield** [comment]
This blocks running the CNN on P4F #396

**Comment by antonyharfield** [comment]
Solution:
1. Delete all unavailable segments from Core
2. Delete same set of unavailable segments from Arbimon
3. Delete all but 1 duplicate available segments from Core
4. Delete the same set of duplicate available segments from Arbimon

**Comment by rassokhin-s** [comment]
Backup data:

[HH_AUD059_unavailable_segments.csv](https://github.com/rfcx/engineering-support/files/12315452/HH_AUD059_unavailable_segments.csv)


[HH_AUD059_unavailable_recordings.csv](https://github.com/rfcx/engineering-support/files/12317000/HH_AUD059_unavailable_recordings.csv)


[HH_AUD059_duplicate_segments.csv](https://github.com/rfcx/engineering-support/files/12317059/HH_AUD059_duplicate_segments.csv)


[HH_AUD059_duplicate_recordings.csv](https://github.com/rfcx/engineering-support/files/12317061/HH_AUD059_duplicate_recordings.csv)

**Comment by rassokhin-s** [comment]
This is done

**Comment by koonchaya** [comment]
@rassokhin-s There is another site that is the same case HULU KAPAS AUD024. There are 287 files corrupted in this site.

HULU KAPAS AUD024 (ojufem6lekbr)
2023/03/01 287 20230301_070000.WAV 20230302_065500.WAV

**Comment by antonyharfield** [comment]
Re-run analysis

```
Hutan Harapan (P4F)


Corrupted files by site

HULU KAPAS AUD049 (62knhpm3fadx)
   2023/03/02 1 20230303_005500.WAV 20230303_005500.WAV

HULU KAPAS AUD043 (ab31tap7jeq0)
   2023/03/06 1 20230306_114500.WAV 20230306_114500.WAV

HULU KAPAS AUD047 (q1xqaif4qyqy)
   2023/02/06 1 20230206_151000.WAV 20230206_151000.WAV

HULU KAPAS AUD060 (vn57la9kuqhd)
   2023/01/15 1 20230115_081500.WAV 20230115_081500.WAV

bato au 82 (0werjowbk54l)
   2023/03/02 1 20230302_163500.WAV 20230302_163500.WAV

HULU KAPAS AUD003 (nzr9ff4h0ffl)
   2023/01/04 3 20230104_100500.WAV 20230104_163000.WAV
   2023/01/05 2 20230105_231000.WAV 20230105_231500.WAV
   2023/01/06 1 20230106_185500.WAV 20230106_185500.WAV

HH_AUD054 (hydi2au0s07d)
   2023/03/01 1 20230301_120000.WAV 20230301_120000.WAV

HH_AUD080 (fs4r8j63ryii)
   2023/03/03 1 20230303_214000.WAV 20230303_214000.WAV

HH_AUD096 (iewvjt06rrwr)
   2023/03/04 1 20230304_074500.WAV 20230304_074500.WAV
   2023/03/05 1 20230305_233500.WAV 20230305_233500.WAV
   2023/03/06 1 20230306_070500.WAV 20230306_070500.WAV

HULU KAPAS AUD024 (ojufem6lekbr)
   2023/03/01 287 20230301_070000.WAV 20230302_065500.WAV

kapas (uwt3l308rvoq)
   2023/03/06 68 20230306_070000.WAV 20230306_123500.WAV

HULU KAPAS AUD041A (mm0qjevukg7r)
   2023/01/10 2 20230110_174500.WAV 20230110_175000.WAV

HULU KAPAS AUD038 (n45la522uy8s)
   2023/03/06 1 20230306_114500.WAV 20230306_114500.WAV

HULU KAPAS AUD076 (dtampl8sc82z)
   2023/01/06 1 20230107_031000.WAV 20230107_031000.WAV

Summary

total files = 1355706
number of corrupted files = 375
```

**Comment by antonyharfield** [comment]
@rassokhin-s: We've got some other sites to fix too

> We can see the problem affects ~1,500 recordings, mostly in HH_AUD059 but also in a few other sites

**Comment by rassokhin-s** [comment]
Steps:
1. Run query and export unavailable segments for backup:
```
SELECT * FROM stream_segments ss WHERE ss.stream_id = 'nnv4kk0latf5' AND ss.start between '2023-01-01' and '2023-05-01' and ss.availability = 0;
```
2. Run query to get all recordings uris. Save result into csv file for further usage
```
select concat(extract(year from start), '/', lpad(extract(month from start)::text, 2, '0'), '/', lpad(extract(day from start)::text, 2, '0'), '/', ss.stream_id, '/', ss.id, fe.value) as uri from stream_segments ss join file_extensions fe on ss.file_extension_id = fe.id where ss.stream_id = 'nnv4kk0latf5' and ss.start between '2023-01-01' and '2023-05-01' and ss.availability = 0;
```
3. Run query to delete segments:
```
DELETE FROM stream_segments ss WHERE ss.stream_id = 'nnv4kk0latf5' AND ss.start between '2023-01-01' and '2023-05-01' and ss.availability = 0;
```
4. Run query in MySQL and export unavailable recordings (get uris from step 2):
```
SELECT * FROM recordings WHERE uri IN ('2023/03/01/nnv4kk0latf5/27c88195-3e86-4146-bab3-dec81ea3cbaf.flac',
'2023/03/01/nnv4kk0latf5/27c88195-3e86-4146-bab3-dec81ea3cbaf.flac', ...);
```
5. Run query in MySQL to delete unavailable recordings:
```
DELETE FROM recordings WHERE uri IN ('2023/03/01/nnv4kk0latf5/27c88195-3e86-4146-bab3-dec81ea3cbaf.flac',
'2023/03/01/nnv4kk0latf5/27c88195-3e86-4146-bab3-dec81ea3cbaf.flac', ...);
```
6. Run query and export duplicate segments for backup:
```
SELECT * FROM public.stream_segments c
JOIN (
	SELECT a.start, a.stream_id, a.created_at FROM public.stream_segments a
	JOIN (SELECT start, stream_id, COUNT(*)
	FROM public.stream_segments
	  WHERE stream_id = 'nnv4kk0latf5' AND start between '2023-01-01' and '2023-05-01'
	GROUP BY start, stream_id
	HAVING count(*) > 1 ) b
	ON a.start = b.start
	AND a.stream_id = b.stream_id
	WHERE a.stream_id = 'nnv4kk0latf5' AND a.start between '2023-01-01' and '2023-05-01'
) d
ON c.start = d.start
AND c.stream_id = d.stream_id
AND c.created_at > d.created_at
join file_extensions fe on c.file_extension_id = fe.id
WHERE c.stream_id = 'nnv4kk0latf5' AND c.start between '2023-01-01' and '2023-05-01'
ORDER BY c.start;
```
7. Run query to get all recordings uris. Save result into csv for further usage:
```
SELECT concat(extract(year from c.start), '/', lpad(extract(month from c.start)::text, 2, '0'), '/', lpad(extract(day from c.start)::text, 2, '0'), '/', c.stream_id, '/', c.id, fe.value) as uri FROM public.stream_segments c
JOIN (
	SELECT a.start, a.stream_id, a.created_at FROM public.stream_segments a
	JOIN (SELECT start, stream_id, COUNT(*)
	FROM public.stream_segments
	  WHERE stream_id = 'nnv4kk0latf5' AND start between '2023-01-01' and '2023-05-01'
	GROUP BY start, stream_id
	HAVING count(*) > 1 ) b
	ON a.start = b.start
	AND a.stream_id = b.stream_id
	WHERE a.stream_id = 'nnv4kk0latf5' AND a.start between '2023-01-01' and '2023-05-01'
) d
ON c.start = d.start
AND c.stream_id = d.stream_id
AND c.created_at > d.created_at
join file_extensions fe on c.file_extension_id = fe.id
WHERE c.stream_id = 'nnv4kk0latf5' AND c.start between '2023-01-01' and '2023-05-01'
ORDER BY c.start;
```
8. Run query to delete duplicate segments:
```
DELETE FROM public.stream_segments WHERE stream_id = 'nnv4kk0latf5' AND start between '2023-01-01' and '2023-05-01' and id IN (
SELECT id FROM public.stream_segments c
JOIN (
	SELECT a.start, a.stream_id, a.created_at FROM public.stream_segments a
	JOIN (SELECT start, stream_id, COUNT(*)
	FROM public.stream_segments
	  WHERE stream_id = 'nnv4kk0latf5' AND start between '2023-01-01' and '2023-05-01'
	GROUP BY start, stream_id
	HAVING count(*) > 1 ) b
	ON a.start = b.start
	AND a.stream_id = b.stream_id
	WHERE a.stream_id = 'nnv4kk0latf5' AND a.start between '2023-01-01' and '2023-05-01'
) d
ON c.start = d.start
AND c.stream_id = d.stream_id
AND c.created_at > d.created_at
WHERE c.stream_id = 'nnv4kk0latf5' AND c.start between '2023-01-01' and '2023-05-01')
```
9. Run query in MySQL and export duplicate recordings (get uris from step 7):
```
SELECT * FROM recordings WHERE uri IN ('2023/03/01/nnv4kk0latf5/27c88195-3e86-4146-bab3-dec81ea3cbaf.flac',
'2023/03/01/nnv4kk0latf5/27c88195-3e86-4146-bab3-dec81ea3cbaf.flac', ...);
```
10. Run query in MySQL to delete unavailable recordings:
```
DELETE FROM recordings WHERE uri IN ('2023/03/01/nnv4kk0latf5/27c88195-3e86-4146-bab3-dec81ea3cbaf.flac',
'2023/03/01/nnv4kk0latf5/27c88195-3e86-4146-bab3-dec81ea3cbaf.flac', ...);
```
11. Run query to delete stream_source files which don't have any segments assigned:
```
delete from stream_source_files where stream_id = 'nnv4kk0latf5' and id in (select sf.id from stream_source_files sf join stream_segments ss ON ss.stream_source_file_id = sf.id WHERE sf.stream_id = 'nnv4kk0latf5' AND ss.start between '2023-01-01' and '2023-05-01' and ss is null);
```

**Comment by rassokhin-s** [comment]
Progress:

HULU KAPAS AUD049 (62knhpm3fadx) **in progress**
   2023/03/02 1 20230303_005500.WAV 20230303_005500.WAV

HULU KAPAS AUD043 (ab31tap7jeq0)
   2023/03/06 1 20230306_114500.WAV 20230306_114500.WAV

HULU KAPAS AUD047 (q1xqaif4qyqy)
   2023/02/06 1 20230206_151000.WAV 20230206_151000.WAV

HULU KAPAS AUD060 (vn57la9kuqhd)
   2023/01/15 1 20230115_081500.WAV 20230115_081500.WAV

bato au 82 (0werjowbk54l)
   2023/03/02 1 20230302_163500.WAV 20230302_163500.WAV

HULU KAPAS AUD003 (nzr9ff4h0ffl)
   2023/01/04 3 20230104_100500.WAV 20230104_163000.WAV
   2023/01/05 2 20230105_231000.WAV 20230105_231500.WAV
   2023/01/06 1 20230106_185500.WAV 20230106_185500.WAV

HH_AUD054 (hydi2au0s07d)
   2023/03/01 1 20230301_120000.WAV 20230301_120000.WAV

HH_AUD080 (fs4r8j63ryii)
   2023/03/03 1 20230303_214000.WAV 20230303_214000.WAV

HH_AUD096 (iewvjt06rrwr)
   2023/03/04 1 20230304_074500.WAV 20230304_074500.WAV
   2023/03/05 1 20230305_233500.WAV 20230305_233500.WAV
   2023/03/06 1 20230306_070500.WAV 20230306_070500.WAV

HULU KAPAS AUD024 (ojufem6lekbr)
   2023/03/01 287 20230301_070000.WAV 20230302_065500.WAV

kapas (uwt3l308rvoq)
   2023/03/06 68 20230306_070000.WAV 20230306_123500.WAV

HULU KAPAS AUD041A (mm0qjevukg7r)
   2023/01/10 2 20230110_174500.WAV 20230110_175000.WAV

HULU KAPAS AUD038 (n45la522uy8s)
   2023/03/06 1 20230306_114500.WAV 20230306_114500.WAV

HULU KAPAS AUD076 (dtampl8sc82z)
   2023/01/06 1 20230107_031000.WAV 20230107_031000.WAV

**Comment by rassokhin-s** [comment]
@koonchaya please check again

**Comment by koonchaya** [comment]
@rassokhin-s I checked site HULU KAPAS AUD024 and the recordings still unavailable. I reuploaded 1 file to test out and nothing happened. The file still unavailable and there is no duplicate either. What can we do to get these files available again?

**Comment by rassokhin-s** [comment]
Backup files from yesterday



[dtampl8sc82z_unavail_recs.csv](https://github.com/rfcx/engineering-support/files/12342623/dtampl8sc82z_unavail_recs.csv)
[dtampl8sc82z_unavail_segs.csv](https://github.com/rfcx/engineering-support/files/12342618/dtampl8sc82z_unavail_segs.csv)
[n45la522uy8s_unavail_recs.csv](https://github.com/rfcx/engineering-support/files/12342624/n45la522uy8s_unavail_recs.csv)
[n45la522uy8s_unavail_segs.csv](https://github.com/rfcx/engineering-support/files/12342625/n45la522uy8s_unavail_segs.csv)
[mm0qjevukg7r_unavail_segs.csv](https://github.com/rfcx/engineering-support/files/12342621/mm0qjevukg7r_unavail_segs.csv)
[uwt3l308rvoq_unavail_uris.csv](https://github.com/rfcx/engineering-support/files/12342629/uwt3l308rvoq_unavail_uris.csv)
[uwt3l308rvoq_unavail_segs.csv](https://github.com/rfcx/engineering-support/files/12342622/uwt3l308rvoq_unavail_segs.csv)
[ojufem6lekbr_unavail_uris.csv](https://github.com/rfcx/engineering-support/files/12342627/ojufem6lekbr_unavail_uris.csv)
[ojufem6lekbr_unavail_segs.csv](https://github.com/rfcx/engineering-support/files/12342619/ojufem6lekbr_unavail_segs.csv)
[iewvjt06rrwr_unavail_segs.csv](https://github.com/rfcx/engineering-support/files/12342631/iewvjt06rrwr_unavail_segs.csv)
[fs4r8j63ryii_unavail_recs.csv](https://github.com/rfcx/engineering-support/files/12342620/fs4r8j63ryii_unavail_recs.csv)
[fs4r8j63ryii_unavail_segs.csv](https://github.com/rfcx/engineering-support/files/12342630/fs4r8j63ryii_unavail_segs.csv)
[hydi2au0s07d_unavail_segs.csv](https://github.com/rfcx/engineering-support/files/12342633/hydi2au0s07d_unavail_segs.csv)
[nzr9ff4h0ffl_unavail_recs.csv](https://github.com/rfcx/engineering-support/files/12342636/nzr9ff4h0ffl_unavail_recs.csv)
[nzr9ff4h0ffl_unavail_segs.csv](https://github.com/rfcx/engineering-support/files/12342632/nzr9ff4h0ffl_unavail_segs.csv)
[0werjowbk54l_unavail_recs.csv](https://github.com/rfcx/engineering-support/files/12342626/0werjowbk54l_unavail_recs.csv)
[0werjowbk54l_unavail_segs.csv](https://github.com/rfcx/engineering-support/files/12342639/0werjowbk54l_unavail_segs.csv)
[vn57la9kuqhd_duplicate_segs.csv](https://github.com/rfcx/engineering-support/files/12342634/vn57la9kuqhd_duplicate_segs.csv)
[vn57la9kuqhd_unavail_segs.csv](https://github.com/rfcx/engineering-support/files/12342635/vn57la9kuqhd_unavail_segs.csv)
[q1xqaif4qyqy_duplicate_recs.csv](https://github.com/rfcx/engineering-support/files/12342637/q1xqaif4qyqy_duplicate_recs.csv)
[q1xqaif4qyqy_duplicate_segs.csv](https://github.com/rfcx/engineering-support/files/12342628/q1xqaif4qyqy_duplicate_segs.csv)
[q1xqaif4qyqy_unavail_recs.csv](https://github.com/rfcx/engineering-support/files/12342642/q1xqaif4qyqy_unavail_recs.csv)
[q1xqaif4qyqy_unavail_segs.csv](https://github.com/rfcx/engineering-support/files/12342644/q1xqaif4qyqy_unavail_segs.csv)
[ab31tap7jeq0_unavail_recs.csv](https://github.com/rfcx/engineering-support/files/12342640/ab31tap7jeq0_unavail_recs.csv)
[ab31tap7jeq0_unavail_seg.csv](https://github.com/rfcx/engineering-support/files/12342641/ab31tap7jeq0_unavail_seg.csv)
[62knhpm3fadx_unavail_recordings.csv](https://github.com/rfcx/engineering-support/files/12342643/62knhpm3fadx_unavail_recordings.csv)
[62knhpm3fadx_unavail_seg.csv](https://github.com/rfcx/engineering-support/files/12342638/62knhpm3fadx_unavail_seg.csv)
