### ISSUE TITLE
Fix timestamp for Croatia project

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#405]
Related issue https://github.com/rfcx/engineering-support/issues/400

Project: https://arbimon.rfcx.org/project/watchout-kopacki-rit-nature-park-croatia

Fix timestamp in these following sites by -2 hours
- HW_028 (ltydv3hkry52)
- HW_099 (pukwpuif98yz)

**Comment by rassokhin-s** [comment]
@koonchaya done

**Comment by koonchaya** [comment]
@rassokhin-s  The first file of those sites still have incorrect timestamps. Please fix them.

![Image](https://github.com/rfcx/engineering-support/assets/87486094/dc9f5c49-54c5-4136-b38c-adecc7cf8b01)
![Image](https://github.com/rfcx/engineering-support/assets/87486094/de60dc72-3dd4-465a-a636-b21b6452a8ef)
