### ISSUE TITLE
Fix timestamp for Parakeets in crops Chile project

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#410]
Original post: jagodoyg@gmail.com

**Description**

Fix timestamp in https://arbimon.rfcx.org/project/parakeets-in-crops-chile/audiodata/recordings by -1 hour

Site names:

- Purriguin : range 20221203_070000 to 20221209_180000
- Sta Rita Collico : the whole site (20221105_080000 to 20221221_080645)

Is it possible to run script checking the project for other site that have the same issue?

**Comment by rassokhin-s** [comment]
This is done @koonchaya
