### ISSUE TITLE
Gombe site timezones are incorrect again

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/engineering-support#415]
Please read Slack conversation for context: https://rfcx.slack.com/archives/C03FD1WD02J/p1693476386714219

The same problem happened back in February: rfcx/arbimon#1167

As mentioned in the previous ticket, we need to find a way to stop this happening again.

Resolution step 1:
- Correct the site timezone in Core `streams` table for this project (all should be +3)
- Make same change in Arbimon `sites` table
- Ensure all `recordings` have `datetime = datetime_utc + 3`

Resolution step 2:
- Ensure that the timezone doesn't change again

**Comment by rassokhina-e** [comment]
The timezone was changed to UTC+3 for all sites! `13789` recordings with not correct offset UTC+2
