### ISSUE TITLE
Fix sync problem between Core and Arbimon for uploading files

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#416]
Original issue:
User uploaded files with Uploader and it showed less files in Arbimon. For example, user uploaded 1000 files but showed 5 files in Arbimon.

Related ticket
- https://github.com/rfcx/arbimon/issues/1304
- https://github.com/rfcx/arbimon/issues/1187

**Comment by rassokhin-s** [comment]
@koonchaya I have commented in these two tasks.
