### ISSUE TITLE
Run soundscape for the DGFC_Malaysia_Sabah_Acoustic Monitoring project

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#422]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1695231360375739

Description

We need to run this job as soon as possible. Sci team needs this job done by Monday 25 Sep and they are under deadline.

Run soundscape in https://arbimon.rfcx.org/project/dgfc-malaysia-sabah-acoustic-monitoring/dashboard 
Project id: `0cyons771mvx`

Parameters:

- Aggregation: time of the day
- Bin size: 344Hz
- Visualization Scale: Normalized
- Frequency: 0kHz
- Amplitude Threshold: 0.05
- Playlist: March to April 2022 (done)
- **Playlist#2: Nov and Dec 2022**
- **Playlist#3: Jan and March 2023**

Sites:
AM Batangan
AM Kaboi Lake Active Site
AM Kaboi Lake Forest
AM Kaboi Lake Forest2 Old Site
AM Kaboi Lake Restored - playlist until 26th January 2023. Recordings with issues after this date.
AM Kaboi Stumping Active Site
AM Kaboi Stumping Forest
AM Kaboi Stumping Forest Old Site
AM Kaboi Stumping Restored
AM Laab Active + Restored
AM Laab Forest
AM Laab Swamp Active Site
AM Laab Swamp Forest Old Site
AM Lot 10a
AM Lot 6a
AM Lot 6b
AM Lot 8
AM Lot 9
AM Lot10b
AM Lot10e
AM WNC 5.1
AM WNC11
AM WNC17
AMKL1
Hillco Audiomoth - playlist until 28th January 2023. Recordings with issues after this date.

**Comment by antonyharfield** [comment]
There are only 9 sites with recordings in March or April 2022.

```
AM Kaboi Lake Active Site
AM Kaboi Lake Forest
AM Kaboi Lake Forest2 Old Site
AM Kaboi Lake Restored
AM Kaboi Stumping Active Site
AM Kaboi Stumping Forest Old Site
AM Kaboi Stumping Restored
AM Laab Swamp Active Site
AM Laab Swamp Forest Old Site
```

**Comment by koonchaya** [comment]
@antonyharfield Please run 2 more playlists (#2 and #3)

**Comment by koonchaya** [comment]
Need to resume 10 cancelled jobs after the more priority jobs are done.
