### ISSUE TITLE
Create slack channels for Tiffany

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#430]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1695670168277209

Please help me create a slack channel named "T4SG-UX-0923" and invite the following as guest users:	
Hannah Park <[hpark@college.harvard.edu](mailto:hpark@college.harvard.edu)>,
Evelyn Ma <[evelynma@college.harvard.edu](mailto:evelynma@college.harvard.edu)>,
Lei Hanna <[leihanna@college.harvard.edu](mailto:leihanna@college.harvard.edu)>

**Comment by antonyharfield** [comment]
Done
