### ISSUE TITLE
Sync - Make Noon to be able to resync the project from the github action

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#437]

**Comment by naluinui** [comment]
Was just discussing this with @antonyharfield, Instead of Github actions, we will add this to the admin page. 

Proposed UI
![Screenshot 2567-03-04 at 12 35 18](https://github.com/rfcx/engineering-support/assets/9149523/85cc3794-aba7-42ad-af42-d97d1a930749)

**Comment by naluinui** [comment]
We may need a way to see the progress of the sync. [TBD]
