### ISSUE TITLE
Run timestamps scripts "DEEP PROJECT SUMATRA" project

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#445]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1697551013032099
By Lola

Project: https://arbimon.rfcx.org/project/deep-project-sumatra/dashboard
Project id: `debyxrah9of7`

**Comment by antonyharfield** [comment]
It looks ok

```
Summary

mismatches sites =
other meta mismatch sites =
  T05_S5 qjsagld6hrsl
exception sites =
  FE07 9klhlltk2ije
  exT16_S2 7sb82ggwqrzs
  exT16_S3 nexq986u525p
total sites =  90
total oks = 424
total mismatches = 0
total others = 6
total exceptions = 8
```

**Comment by antonyharfield** [comment]
There are some unavailable recordings for the following sites:
- T05_S5
- exT16_S2
- exT16_S3
