### ISSUE TITLE
Query impact numbers

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#453]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1698708380833609
Request by: Carly

Could you please query the following for our quarterly impact numbers update:
1. number of unique species represented in the public template library
2. total number of arbimon users to date
3. number of active arbimon users (# of users who have at least logged in, in the last 3 months)
4. number of threatened species detected in Arbimon (iucn status of critically endangered, endangered, vulnerable, near threatened)

This should be done by Nov16

**Comment by grindarius** [comment]
> number of unique species represented in the public template library

query
```sql
select
	count(distinct species.species_id)
from templates
inner join projects on templates.project_id = projects.project_id 
inner join species on templates.species_id = species.species_id
where templates.deleted is not null and templates.deleted = 0 and projects.is_private = false
```
result: `2298`

> total number of arbimon users to date

query
```sql
select count(users.user_id) from users
```
result: `6031`

> number of active arbimon users (# of users who have at least logged in, in the last 3 months)

query
```sql
select count(users.user_id) from users where users.last_login > date_sub(curdate(), interval 3 month)
```
result: `1110`


> number of threatened species detected in Arbimon (iucn status of critically endangered, endangered, vulnerable, near threatened)

query
```sql
select count(taxon_species_id) from taxon_species_iucn where risk_rating_iucn_id = 600 or risk_rating_iucn_id = 500 or risk_rating_iucn_id = 400 or risk_rating_iucn_id = 300
```

result: `6118`

**Comment by koonchaya** [comment]
1. number of unique species represented in the public template library = It should be the number of species with iucn status of critically endangered or endangered or vulnerable or near threatened
2. number of threatened species detected in Arbimon (iucn status of critically endangered, endangered, vulnerable, near threatened) = should be arbimon-wide, all threatened species detected in arbimon (not public template library)

**Comment by koonchaya** [comment]
1. number of unique species represented in the public template library = 2298
2. total number of arbimon users to date = 6031
3. number of active arbimon users (# of users who have at least logged in, in the last 3 months) = 1110
4. number of threatened species detected in Arbimon (iucn status of critically endangered, endangered, vulnerable, near threatened) = 396
