### ISSUE TITLE
Run timestamps for WatchOut - Kopacki rit Nature Park, Croatia

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#466]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1699969935192409

Project https://arbimon.rfcx.org/project/watchout-kopacki-rit-nature-park-croatia/dashboard
Project id `9n2rzxinyz8z `

Run timestamps of the 3rd round uploading.
Upload information sheet https://docs.google.com/spreadsheets/d/1i6v9qZKm8SDfWR_peqhRiIi2midRfPFD/edit#gid=1454248811

**Comment by antonyharfield** [comment]
All ok.
