### ISSUE TITLE
Hide Panthera onca species detections on Mexico Tech4Nature project

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#472]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1699997853170529
Reported by: Carly

For the Mexico Tech4Nature project, could you please mask the GPS coordinates for jaguar (Panthera onca) detections? On Insights and Arbimon. https://arbimon.rfcx.org/project/tech4nature-mexico/dashboard
The partners will be releasing a report on the project at the end of the month and we need the Insights page to be public for that, but the partners don't want it to be public unless jaguar sites are hidden.

This should be done by Nov30

**Comment by naluinui** [comment]
Hi Noon. We updated the local risk rating status of Panthera onca in Tech4Nature Mexico to be Critically Endangered. All the location information of the species should be hidden to non-project members.

**Comment by naluinui** [comment]
Extra solution we can add to this is adding the Local in to the tag to indicate that this risk rating is defined locally

![Screen Shot 2566-11-23 at 12 29 39](https://github.com/rfcx/engineering-support/assets/9149523/8a3c1029-0e44-4523-b6bd-a6efcdab3811)

I'm not sure how the user would feel about this. May need to discuss with sci team & UX?

**Comment by koonchaya** [comment]
Will this tag work the same as CR?
