### ISSUE TITLE
Fix audio uploaded to wrong sites in PR project

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/engineering-support#482]
Reported by @krisharmon on eng-support

> Recordings from June-July 2022 for 4 Puerto Rico Guardians have been uploaded to the incorrect sites in Arbimon.
> Sites TO01, TO04, TO05, TO06 each have audio from TOG1, TOG4, TOG5, TOG6.
> 
> Steps to reproduce:
> Go to Arbimon and look at the recordings available from 2022 for the 4 sites mentioned above and compare that with the field data sheet for that deployment. Screenshots will be included for convenience in the comment for this post.
> 
> Expected result:
> The aforementioned sites will only have recordings collected between 2022_04_04 and 2022_04_13.
> 
> Actual result:
> There are recordings for the appropriate dates, plus recordings from 2022_06_16 to 2022_07_31.
> 
> Additional details:
> Project: Puerto Rico Island-Wide
> url: https://arbimon.rfcx.org/project/puerto-rico-island-wide/visualizer/rec/144850670

**Comment by antonyharfield** [comment]
Additional information provided by Kris in the issue thread

1. plot of recordings for sites in TO

![Image](https://github.com/rfcx/engineering-support/assets/1175362/c68fc2b3-a4f3-4079-a6f4-e27915c61735)


2. field data sheet with deployment days for the sites in question

![Image](https://github.com/rfcx/engineering-support/assets/1175362/7a4bf875-605e-4dc4-8f66-4573a7486b16)


3. screenshot of TO01

![Image](https://github.com/rfcx/engineering-support/assets/1175362/a86922cc-f42e-4476-9a3c-c23116a47ce5)

4. screenshot of TO04

![Image](https://github.com/rfcx/engineering-support/assets/1175362/d3f1cd20-efbc-4e3d-892f-195439a7bf4b)

5. screenshot of TO05

![Image](https://github.com/rfcx/engineering-support/assets/1175362/7c7f0387-d2d1-4ed2-b928-88b8b65eb7f9)

6. screenshot of TO06

![Image](https://github.com/rfcx/engineering-support/assets/1175362/8731e477-18a5-4771-84ef-c25a6f380ec6)

> Note the reduced sampling rate (12 kHz instead of 24 kHz), Guardian ID in the filenames, and calendar with recordings by date in each of the screenshots.

**Comment by koonchaya** [comment]
It can be my mistake uploaded files into the wrong sites. I will go through and delete files that not belong to the sites and upload files to the correct sites.

**Comment by koonchaya** [comment]
- [ ] Removed files in June and July 2022 from sites: TO01, TO04, TO05, TO06

- [ ] Upload files n June and July 2022 to sites: TO01, TO04, TO05, TO06
