### ISSUE TITLE
Show PR CNN results in PM for Jun, Jul, Aug

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/engineering-support#487]
The CNN jobs for PR are (almost) complete for Jun, Jul, Aug. Next step is to transfer top X per site per day to PM for review and then they will also show up in Insights.

**Comment by koonchaya** [comment]
Need to add CNN result from Job#18 to Jun 2022. This is the job from the sites uploaded after the first batch of Jun has started.

**Comment by koonchaya** [comment]
@antonyharfield Jun CNN results are done. Can you combine the Job#14 and #18 for June result? I ran jobs in Sep-Dec. Nov and Dec are done too.

Check here https://bio.rfcx.org/puerto-rico-island-wide/detect/cnn

**Comment by antonyharfield** [comment]
Jun to Aug are showing on PM

https://arbimon.rfcx.org/project/puerto-rico-island-wide/analysis/patternmatching

Need Science Team to check everything looks good.

**Comment by koonchaya** [comment]
Combine all the results Jun-Dec in 1 job for each species.

**Comment by koonchaya** [comment]
@antonyharfield The PM result from Jun to Aug that you transferred to the project are containing ROIs from Mar, Apr, May too. Can you recheck the results?
Example 


![Image](https://github.com/rfcx/engineering-support/assets/87486094/13fcca6e-474c-4256-b259-8aa9f8139a01)



![Image](https://github.com/rfcx/engineering-support/assets/87486094/653ca2fa-c530-4ac8-84ce-1c22f7e3ff5f)



![Image](https://github.com/rfcx/engineering-support/assets/87486094/72d38a10-744f-43dc-aea0-ddca18ecd995)
