### ISSUE TITLE
Query stats numbers for marketing

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#493]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1702999227673819
From: @carlybatist 

Requests
1.	Number of Arbimon **users** added since Jan 1, 2023
2.	Number of Arbimon **projects** added since Jan 1, 2023
3.	Number of **new species detected** since Jan 1, 2023
4.    Number of **new threatened species detected** since Jan 1, 2023 (threatened = IUCN status of Near Threatened OR Vulnerable OR Endangered OR Critically Endangered)
         a. if possible, a list of which threatened species these were
             would be great as well (like the scientific name)
5. Number of **new recordings** added to Arbimon since Jan 1, 2023

It would be awesome if you were able to get these numbers **by Jan 2,** but let me know if this is too quick of a turnaround and when you estimate you would be able to get them.

Additional stats that would be a lovely bonus but NOT necessary if it’s more difficult:
1.	Number of new templates added to the public template library since Jan 1, 2023
        a.   Number of new species represented in the public
         template library since Jan 1, 2023
2.	Which countries had recordings added to Arbimon for the first time in 2023 (e.g., from our impact numbers board we went from having recordings from 114 countries at the end of 2022 to Arbimon having recordings from 119 countries now – what are those 5 countries?)

**Comment by grindarius** [comment]
- Number of Arbimon **users** added since Jan 1, 2023
  - db: production `arbimon2`
  - query:
    ```sql
    select count(*) from users where created_on > '2023-01-01 00:00:00'
    ```
  - result: 2109
- Number of Arbimon **projects** added since Jan 1, 2023
  - db: production  `arbimon2`
  - query:
    ```sql
    select count(*) from species where created_at > '2023-01-01 00:00:00'
    ```
  - result: 1324
- Number of **new species detected** since Jan 1, 2023
  - db: production `arbimon2`
  - query:
    ```sql
    select count(*) from species where created_at > '2023-01-01 00:00:00'
    ```
  - result: 26
 - Number of **new threatened species detected** since Jan 1, 2023
   - db: production `insights`
   - query:
    ```sql
    select
	taxon_species.scientific_name
    from taxon_species
    left join taxon_species_iucn on taxon_species.id = taxon_species_iucn.taxon_species_id
    inner join risk_rating_iucn on taxon_species_iucn.risk_rating_iucn_id = risk_rating_iucn.id
    where taxon_species.created_at > '2023-01-01T00:00:00.000Z' and risk_rating_iucn.is_threatened = true
    ```
  - result: 10, below are the scientific name
    ```
    Craugastor evanesco
    Hemiphractus elioti
    Hemiphractus kaylockae
    Hemiphractus panamensis
    Triprion spinosus
    Ecnomiohyla veraguensis
    Caretta caretta
    Chelonia mydas
    Eretmochelys imbricata
    Lepidochelys olivacea
    ```
- Number of new recordings added to Arbimon since Jan 1, 2023
  - db: production `arbimon2`
  - query:
    ```sql
    select count(*) from recordings where upload_time > '2023-01-01 00:00:00'
    ```
  - result: 54600942
