### ISSUE TITLE
Run timestamp for Health In Harmony Manombo project

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#495]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1704371414565919
From: Lola

Would you please be able to run the timestamp script on the following project?
Project Name: Health In Harmony Manombo
Project Link: https://arbimon.rfcx.org/project/health-in-harmony-manombo/dashboard

**Comment by antonyharfield** [comment]
```
Summary

mismatches sites =
other meta mismatch sites =
  AM02_P1 jeju750tzlik
  AM03_P1 qityu4ietdiy
  AM12_P2 38o9ptzdjnwf
  AM18_P1 x0r7mncwjopa
  AM22_P1 efraxcaxdro8
  AM24_P1 k3s4w6cbkpxi
exception sites =
  AM40_P1 rw8kdcczshfs
total sites =  49
total oks = 242
total mismatches = 0
total others = 39
total exceptions = 1
```

I can't see any problems with this project. :D
