### ISSUE TITLE
Run timestamp for WeForest Wildlife Corridors project

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#496]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1704472373403879
From: Lola

Can you please run the timestamp script on the following project (only data recorded in 2023)?
https://arbimon.rfcx.org/project/weforest-wildlife-corridors/dashboard

**Comment by antonyharfield** [comment]
No problems

```
Summary

mismatches sites =
other meta mismatch sites =
  IPE35 w730xk5iaius
  IPE47 vxiiv1a8hf9o
  IPE55 kqdqdclh43vn
  IPE61 0qkfm5v2z1r2
  IPE83 yrguheqis6rm
exception sites =
total sites =  127
total oks = 1313
total mismatches = 0
total others = 55
total exceptions = 0
```
