### ISSUE TITLE
Fix timestamps for Health in Harmony project

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#508]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1706120710188369
From: @gabcrax 

Fix timestamps by adding 2 hours to sites (AM03_P1 and AM18_P1)

**Issue description:**
He team,
There are 2 sites (AM03_P1 and AM18_P1) in Health In Harmony Manombo Project that bird species are starting to sing 2 hours earlier than normal. Although the time in the file and in Arbimon are the same.
We need the recordings to be advanced by 2 hours on these 2 sites to be the same as the rest of the sites.

**Steps to reproduce:**
Enter the project, go to Visualizer and select one of the 2 sites and you will notice that from 3 AM onwards the birds species are singing. In other sites the species start singing at 5 AM.

**Expected result:**
It is expected that the bird species will start singing at 5AM.

**Actual result:**
The species are singing at 3AM in both sites (AM03_P1 and AM18_P1).

**Additional details:**
https://arbimon.rfcx.org/project/health-in-harmony-manombo/dashboard

**Comment by rassokhin-s** [comment]
This is done @koonchaya
