### ISSUE TITLE
Fix timestamps for Colombia Humboldt project

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#509]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1705954357074279

Related ticket: https://github.com/rfcx/engineering-support/issues/506

Fix timestamps: the timestamps should match the filename (file meta UTC-5)
Project: https://arbimon.rfcx.org/project/colombia-audiomoth-humboldt-inst/dashboard
Site: P28

**Comment by rassokhin-s** [comment]
Why do you think it should be +1 hour? Meta shows
```
Recorded at 13:30:00 01/11/2023 (UTC-5) 
```

So we need to do +6 hours, no?

<img width="1509" alt="image" src="https://github.com/rfcx/engineering-support/assets/2122991/5516419d-f57c-4d51-ba6c-a966c6640b50">

**Comment by koonchaya** [comment]
It should be uploaded with UTC-5 but the site timezone is now UTC-6.

**Comment by rassokhin-s** [comment]
This should be done now
