### ISSUE TITLE
Get a list of 30 users for Tiff

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#511]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1706742909833159
From: @tiffanylee0125 

Could you help me pull a list of 30 users who:
- Are not from the RFCx team
- Have recently logged in within the past 6 weeks.
- Not repeated in the list from last time (see comment)
- Not part of the unsubscribed list

Example export files from the past https://rfcx.slack.com/archives/C03FD1WD02J/p1706743066244769?thread_ts=1706742909.833159&cid=C03FD1WD02J

**Comment by grindarius** [comment]
I am handing off this issue to Zhenya since she got the mailchimp account to filter the users list by bullet number 4

**Comment by naluinui** [comment]
Can we close this?

**Comment by koonchaya** [comment]
The last task is not done yet. We still need to get Not part of the unsubscribed list for Tiff.

**Comment by naluinui** [comment]
Which are in: 
- https://rfcx.slack.com/archives/G018NMPCBHS/p1707821876590029 
- https://rfcx.slack.com/archives/G018NMPCBHS/p1707821894194149

But that was 25 days ago since Tiff requested it, best make sure if she still wanted it?  @koonchaya

**Comment by koonchaya** [comment]
[unsubscribed_members_export_0686467804.csv](https://github.com/rfcx/engineering-support/files/14428635/unsubscribed_members_export_0686467804.csv)
[unsubscribed_segment_export_d7d7a1406a.csv](https://github.com/rfcx/engineering-support/files/14428634/unsubscribed_segment_export_d7d7a1406a.csv)
[users_2.csv](https://github.com/rfcx/engineering-support/files/14428636/users_2.csv)
