### ISSUE TITLE
CNN job is stuck for ireland-orca project

### ISSUE THREAD

**Issue by koonchaya** [rfcx/engineering-support#515]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1707928583305879
From: @nnbuainain 

I am checking over the weekend.

Issue description:
CNN job for ireland-orca project is stuck

Steps to reproduce:
Go to the job page:
https://arbimon.org/p/orca-ireland/analyse/cnn/detail/33
See the progress bar is not moving. it's been like that since yesterday.

Expected result:
Progress bar should be moving

Actual result:
Job is stuck at 2.21%

Additional details:
https://arbimon.org/p/orca-ireland/analyse/cnn/detail/33

**Comment by antonyharfield** [comment]
Currently on 34%

**Comment by koonchaya** [comment]
@antonyharfield Can you check the progress of this CNN?

**Comment by koonchaya** [comment]
The job is finished but there were no results
