### ISSUE TITLE
Failing CNN job on Santarem

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/engineering-support#517]
Original post: https://rfcx.slack.com/archives/C03FD1WD02J/p1708378015179339
From:  @nnbuainain 

Issue description:
CNN jobs fail

Steps to reproduce:
Go to:
https://arbimon.org/p/santarem/analyse/cnn
Either create a job similar to what you see in the dashboard or just check the status of the current jobs.

Expected result:
To have the CNN jobs running beautiful and fast to deliver to the partners as I promised

Actual result:
I get "Error" on job's status with no further information.

Additional details:
https://arbimon.org/p/santarem/analyse/cnn

Impact on work:
:red_circle: Critical for partner — 1-2 day resolution

![Image](https://github.com/rfcx/engineering-support/assets/1175362/3a8871e4-217a-4136-abcb-c3ad011416c0)

![Image](https://github.com/rfcx/engineering-support/assets/1175362/376ab39d-401d-40e9-bf63-67bd01fed105)

**Comment by antonyharfield** [comment]
Related https://github.com/rfcx/rfcx-api/issues/538

**Comment by koonchaya** [comment]
@antonyharfield Can we close this ticket?

**Comment by koonchaya** [comment]
@antonyharfield will rerun the job without filter.
